{% set name = "biorbd-optim" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyomeca/BiorbdOptim/archive/Release_{{ version }}.tar.gz
  sha256: d19a85b2a8198b4b61e0185c633c3e1bd63d94d6218c87dab1a33734f389ae15

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - {{ cdt('xorg-x11-server-Xvfb') }}  # [linux]
    - {{ cdt('libXtst') }}  # [linux]
  run:
    - python
    - casadi
    - biorbd =*=*casadi*
    - biorbd-viz
    - packaging

test:
  imports:
    - biorbd_optim

about:
  home: http://github.com/pyomeca/BiorbdOptim
  license: Apache-2.0
  license_file: LICENSE
  summary: Biorbd optimal control toolkit
  description: |
    Biorbd optimal control toolkit 
  doc_url: https://github.com/pyomeca/BiorbdOptim
  dev_url: https://github.com/pyomeca/BiorbdOptim

extra:
  recipe-maintainers:
    - pariterre
